/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    CompressView: typeof import('./views/components/CompressView.vue')['default']
    ConvertView: typeof import('./views/components/ConvertView.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    MergeView: typeof import('./views/components/MergeView.vue')['default']
    PdfEditorView: typeof import('./views/PdfEditorView.vue')['default']
    PdfFileList: typeof import('./views/components/PdfFileList.vue')['default']
    PdfWorkspace: typeof import('./views/PdfWorkspace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitView: typeof import('./views/components/SplitView.vue')['default']
    SystemSettingDialog: typeof import('./views/components/dialog/SystemSettingDialog.vue')['default']
    ToolboxView: typeof import('./views/ToolboxView.vue')['default']
    WatermarkView: typeof import('./views/components/WatermarkView.vue')['default']
  }
}
