/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    CompressView: typeof import('./views/components/CompressView.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    MergeView: typeof import('./views/components/MergeView.vue')['default']
    PdfFileList: typeof import('./views/components/PdfFileList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemSettingDialog: typeof import('./views/components/dialog/SystemSettingDialog.vue')['default']
  }
}
